server:
  port: 8761
eureka:
  server:
    renewal-percent-threshold: 0.49
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false

management:
  context-path: /manage

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf 
