server:
  port: 8761
eureka:
  instance:
    hostname: springboot-eureka.demo-service.svc
  server:
    renewal-percent-threshold: 0.49
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  context-path: /manage

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf 
