server:
  port: 8080
eureka:
# instance:
#    hostname: ${OPENSHIFT_APP_DNS}
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false

management:
  context-path: /manage

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf 
